### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by ghost** [Twoure/KissManga.bundle#2]
this works great, but can you please create a single one for : http://kisscartoon.me/ ?
this project : https://github.com/Twoure/KissNetwork.bundle doesnt seem to be working - it also has other extra stuff which is not suitable to younger kids. 
can you please make modifications to this one so it only displays content from http://kisscartoon.me/?

I tried changing the base url in the `\code\..py` but I think there is more to it. 
thanks

**Comment by Twoure** [comment]
I can make a Prefs setting that allows you to select the sites for KissNetwork?  It would then only show directories for the sites picked.  Would that suffice?

If not you can always check out https://github.com/jwsolve/KissCartoons.bundle and/or I'll take a look into some kind of password protection.  Think https://github.com/coder-alpha/CcloudTv.bundle implements some kind of password section for adult stuff.

**Comment by ghost** [comment]
thanks for your response, yes, that would work as well. 
I tried https://github.com/jwsolve/KissCartoons.bundle project but it is not very organized. once the app is open, there are are hundreds of shows to choose from, for example each season for a show is show up in the list instead of falling under a single show name. Also there is no bookmark functionality.

**Comment by Twoure** [comment]
Yes I'm also annoyed by the season issue with the kiss sites and have started to work on a solution.  This is inherent to the sites and is not easily solved.  Also I agree with having bookmarks, think they should be included whenever possible.  I don't enjoy having to re-search for media ever time I want to access it.

**Comment by Twoure** [comment]
Going to close this issue now since it's more related to my [KissNetwork.bundle](https://github.com/Twoure/KissNetwork.bundle) channel.  I included the site [option](https://github.com/Twoure/KissNetwork.bundle/commit/edd20f6c6e16d3c72e91b2dc31e4e4ec4b757868) as discussed.  If you want it changed or see a better way, open an issue on the [KissNetwork.bundle](https://github.com/Twoure/KissNetwork.bundle) channel.  Thanks
